### ISSUE TITLE
Chapter 2 to-do list

### ISSUE THREAD

**Issue by rpruim** [rpruim/ula-ds#2]
* [ ] Check exercises
    * [ ] is there a good sage replacement for the numerical precision stuff? 
* [ ] Move Python Practices earlier
* [ ] Add solution to new example (answer is already there)
* [ ] Decide what to say about symbolic nature of sympy (or find another RREF function).
